# Site settings
title: Josh Freed
email: joshfreed3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a mobile application developer for your small or medium business. I specialize in building iOS
  applications for the iPhone, iPad, and Apple Watch.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joshua-freed.com" # the base hostname & protocol for your site
twitter_username: jfreed33
github_username:  joshfreed

# Build settings
markdown: kramdown
